cloudCredentialsSecretName: cloud-credentials

hcloud:
  zone: eu-central
  imageName: ubuntu-24.04
  sshHKeyPairName: kubeaid

bareMetal:
  wipeDisks: false
  installImage:
    imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz
    vg0:
      size: 25G
      rootVolumeSize: 10G
  sshKeyPair:
    name: kubeaid
    secretName: hetzner-ssh-keypair

controlPlane:
  regions:
    - fsn1
    - nbg1
    - hel1

  hcloud:
    machineType: cax11
    replicas: 3
    loadBalancer:
      enabled: true
      region: hel1

nodeGroups:
  bareMetal: []
  hcloud: []
