{{- if eq .Values.mode "bare-metal" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  annotations:
    # Use fixed node names for bare metal servers, since there are storage integrations that allow
    # you to use the storage of the bare metal servers and that work with fixed node names.
    capi.syself.com/constant-bare-metal-hostname: "true"
spec:
  template:
    {{/* Currently, Cluster API Provider Hetzner (CAPH) doesn't support having the metadata field
         here. I've opened an issue for this here : https://github.com/syself/cluster-api-provider-hetzner/issues/1680. */}}
    {{/* metadata: */}}
    {{/*   labels: */}}
    {{/*     node.cluster.x-k8s.io/cloud-provider: hetzner-bare-metal */}}
    spec:
      hostSelector:
        matchLabels:
          role: {{ $.Values.global.clusterName }}-control-plane
      installImage:
        image:
          path: {{ .Values.bareMetal.installImage.imagePath }}
        partitions:
          - fileSystem: esp
            mount: /boot/efi
            size: 512M
          - fileSystem: ext4
            mount: /boot
            size: 1024M
          # Logical Volume Group.
          - fileSystem: vg0
            mount: lvm
            size: {{ .Values.bareMetal.installImage.vg0.size }}
        logicalVolumeDefinitions:
          # The Operating System (OS).
          - vg: vg0
            name: root
            mount: /
            filesystem: ext4
            size: {{ .Values.bareMetal.installImage.vg0.rootVolumeSize }}
        postInstallScript: |
          #!/bin/bash

          {{/* Give highest priority to the Network Card / Connection entry in the boot order.
               Otherwise, we cannot boot the servers into rescue mode, and need to reach out to the
               Hetzner support team. */}}
          NETBOOT=$(efibootmgr -v \
            | grep -E "Network (Card|Connection)" \
            | sed 's/Boot\([0-9A-F]*\).*/\1/' \
            | head -n1)
          CURRENT_ORDER=$(efibootmgr | grep "BootOrder:" | cut -d' ' -f2)
          NEW_ORDER=$(echo "$CURRENT_ORDER" | sed "s/$NETBOOT,\?//g" | sed "s/^/$NETBOOT,/" | sed 's/,$//')
          efibootmgr -o $NEW_ORDER

          mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg

          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils

          cloud-init clean --logs
        swraid: 1
        swraidLevel: {{ (.Values.controlPlane.bareMetal.raid).level | default 1 }}
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: {{ $.Values.bareMetal.sshKeyPair.secretName }}
{{- end }}

{{- if or (eq .Values.mode "bare-metal") (eq .Values.mode "hybrid") }}
{{- range $nodeGroupIndex, $nodeGroup := $.Values.nodeGroups.bareMetal }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
  annotations:
    # Use fixed node names for bare metal servers, since there are storage integrations that allow
    # you to use the storage of the bare metal servers and that work with fixed node names.
    capi.syself.com/constant-bare-metal-hostname: "true"
spec:
  template:
    {{/* Currently, Cluster API Provider Hetzner (CAPH) doesn't support having the metadata field
         here. I've opened an issue for this here : https://github.com/syself/cluster-api-provider-hetzner/issues/1680. */}}
    {{/* metadata: */}}
    {{/*   labels: */}}
    {{/*     node.cluster.x-k8s.io/cloud-provider: hetzner-bare-metal */}}
    spec:
      hostSelector:
        matchLabels:
          role: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
      installImage:
        image:
          path: {{ $.Values.bareMetal.installImage.imagePath }}
        partitions:
          - fileSystem: esp
            mount: /boot/efi
            size: 512M
          - fileSystem: ext4
            mount: /boot
            size: 1024M
          # Logical Volume Group.
          - fileSystem: vg0
            mount: lvm
            size: {{ $.Values.bareMetal.installImage.vg0.size }}
        logicalVolumeDefinitions:
          # The Operating System (OS).
          - vg: vg0
            name: root
            mount: /
            filesystem: ext4
            size: {{ $.Values.bareMetal.installImage.vg0.rootVolumeSize }}
        postInstallScript: |
          #!/bin/bash

          {{/* Give highest priority to the Network Card / Connection entry in the boot order.
               Otherwise, we cannot boot the servers into rescue mode, and need to reach out to the
               Hetzner support team. */}}
          NETBOOT=$(efibootmgr -v \
            | grep -E "Network (Card|Connection)" \
            | sed 's/Boot\([0-9A-F]*\).*/\1/' \
            | head -n1)
          CURRENT_ORDER=$(efibootmgr | grep "BootOrder:" | cut -d' ' -f2)
          NEW_ORDER=$(echo "$CURRENT_ORDER" | sed "s/$NETBOOT,\?//g" | sed "s/^/$NETBOOT,/" | sed 's/,$//')
          efibootmgr -o $NEW_ORDER

          mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg

          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils

          cloud-init clean --logs
        swraid: 1
        swraidLevel: {{ ($nodeGroup.raid).level | default 1 }}
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: {{ $.Values.bareMetal.sshKeyPair.secretName }}
{{- end }}
{{- end }}
