global:
  kubernetes:
    version: v1.33.0
  clusterAPI:
    version: v1.11.3
  enableClusterAutoscaler: true
  capa:
    version: v2.9.2
    enableMachinePools: false
  caph:
    version: v1.0.7
  capz:
    version: v1.21.1
  kubeaid:
    repo: https://github.com/Obmondo/KubeAid.git
  pods:
    cidrBlock: 10.244.0.0/16

provider:
  hetzner: false
  aws: false
  azure: false
